CREATE SCHEMA IF NOT EXISTS fileway;

CREATE TABLE fileway.user(
                             user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_email VARCHAR(300) NOT NULL,
                             user_password VARCHAR(512) NOT NULL,
                             user_role VARCHAR(255) CHECK ( user_role in ('ROLE_USER', 'ROLE_PREMIUM') )
);

CREATE TABLE fileway.file_link (
                                   file_link_id UUID PRIMARY KEY,
                                   file_link_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                                   file_link_expires_at TIMESTAMPTZ NOT NULL,
                                   file_link_max_uses INT NOT NULL DEFAULT 1 CHECK (file_link_max_uses > 0),
                                   file_link_use_count INT NOT NULL DEFAULT 0 CHECK (file_link_use_count >= 0),
                                   user_id BIGINT,
                                   CONSTRAINT fk_user
                                       FOREIGN KEY (user_id)
                                           REFERENCES fileway."user"(user_id)
);

CREATE TABLE fileway.file (
                              file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              file_size BIGINT NOT NULL CHECK (file_size >= 0),
                              file_storage_name TEXT NOT NULL,
                              file_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                              file_original_name TEXT NOT NULL,
                              file_link_id UUID NOT NULL,
                              CONSTRAINT fk_file_link
                                  FOREIGN KEY (file_link_id)
                                      REFERENCES fileway.file_link(file_link_id)
                                      ON DELETE CASCADE
);